routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('discussion', 'DiscussionController');

Route::resource('/discussion/{discussion}/replies', 'ReplyController');

Route::post('/discussion/{discussion}/replies/{reply}/best-reply', 'DiscussionController@reply')->name('best-reply');

Route::get('user/notifications', 'UserController@notifications')->name('users.notifications');

app/User.php
<?php

namespace App;

use App\Notifications\VerifyEmail;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function discussions()
    {
        return $this->hasMany(Discussion::class);
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function sendEmailVerificationNotification()
    {
        $this->notify(new VerifyEmail());
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    public function notifications()
    {
        // mark all as read
        auth()->user()->unreadNotifications->markAsRead();

        // display all notifications
        return view('users.notifications',[
            'notifications' => auth()->user()->notifications()->paginate(5)
        ]);
    }
}

resources/views/users/notifications.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header bg-danger text-white">Notifications</div>

        <div class="card-body">
            <ul class="list-group">
                @foreach($notifications as $notification)
                    <li class="list-group-item">
                        @if($notification->type === 'App\Notifications\NewReplyAdded')
                            A new reply added to your discussion -
                            <a href="{{ route('discussion.show', $notification->data['discussion']['slug']) }}" class="text-danger lead ml-1">
                                {{ $notification->data['discussion']['title'] }}
                            </a>
                        @endif
                        @if($notification->type === 'App\Notifications\MarkedAsBestReply')
                            your reply on
                                <a href="{{ route('discussion.show', $notification->data['discussion']['slug']) }}" class="text-danger lead mx-1">
                                    {{ $notification->data['discussion']['title'] }}
                                </a>
                            has been marked as best reply
                            @endif
                    </li>
                @endforeach
            </ul>
        </div>
    </div>
@endsection