routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('discussion', 'DiscussionController');

Route::resource('/discussion/{discussion}/replies', 'ReplyController');

Route::post('/discussion/{discussion}/replies/{reply}/best-reply', 'DiscussionController@reply')->name('best-reply');

Route::get('user/notifications', 'UserController@notifications')->name('users.notifications');

app/Discussion.php
<?php

namespace App;

use App\Notifications\MarkedAsBestReply;

class Discussion extends Model
{
    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function bestReply(Reply $reply)
    {
        $this->update([
            'reply_id' => $reply->id
        ]);

        if($this->author->id === $reply->owner->id){
            return;
        }

        $reply->owner->notify(new MarkedAsBestReply($reply->discussion));
    }

    public function getBestReply()
    {
        return $this->belongsTo(Reply::class, 'reply_id');
    }

    public function scopeFilterByChannels($builder)
    {
        if(request()->query('channel')){
            // filter
            $channel = Channel::where('slug', request()->query('channel'))->first();

            if($channel){
                return $builder->where('channel_id', $channel->id);
            }

            return $builder;
        }

        return $builder;
    }
}

app/Http/Controllers/DiscussionController.php
<?php

namespace App\Http\Controllers;

use App\Discussion;
use App\Http\Requests\CreateDiscussionRequest;
use App\Reply;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class DiscussionController extends Controller
{

    public function __construct()
    {
       $this->middleware(['auth', 'verified'])->only(['create', 'store']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('discussion.index', [
            'discussions' => Discussion::filterByChannels()->paginate(3)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('discussion.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateDiscussionRequest $request)
    {
        auth()->user()->discussions()->create([
            'title' => $request->title,
            'content' => $request->content,
            'channel_id' => $request->channel,
            'slug' => Str::slug($request->title)
        ]);

        session()->flash('success', 'Discussion Posted');

        return redirect(route('discussion.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Discussion $discussion)
    {
        return view('discussion.show',[
            'discussion' => $discussion
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function reply(Discussion $discussion, Reply $reply)
    {
        $discussion->bestReply($reply);

        session()->flash('success', 'marked as best reply');

        return redirect()->back();
    }
}

resources/views/discussion/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">Add Discussion</div>

        <div class="card-body">
            <form action="{{ route('discussion.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="title">Title</label>
                    <input id="title" type="text" class="form-control" name="title">
                </div>
                <div class="form-group">
                    <label for="content">Content</label>
                    <input id="content" type="hidden" name="content">
                    <trix-editor input="content"></trix-editor>
                </div>
                <div class="form-group">
                    <label for="channel">Channel</label>
                    <select name="channel" id="channel" class="form-control">
                        @foreach($channels as $channel)
                            <option value="{{ $channel->id }}">{{ $channel->name }}</option>
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-success">Add Discussion</button>
            </form>
        </div>
    </div>
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('css/trix.css') }}">
@endsection
@section('script')
    <script src="{{ asset('js/trix.js') }}"></script>
@endsection

resources/views/discussion/index.blade.php
@extends('layouts.app')

@section('content')

    @foreach($discussions as $discussion)
        <div class="card mb-3">

            @include('partials.discussion-header')

            <div class="card-body">
                <div class="text-center text-info font-weight-bold">{{ $discussion->title }}</div>
            </div>
        </div>
    @endforeach

    {{ $discussions->appends(['channel' => request()->query('channel')])->links() }}

@endsection

resources/views/discussion/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="card mb-5">

        @include('partials.discussion-header')

        <div class="card-body">
            <div class="text-center font-weight-bold text-info">
                {{ $discussion->title }}
            </div>

            <hr>

            {!! $discussion->content !!}

            @if($discussion->getBestReply)
                <div class="card bg-success mt-5 text-white">
                    <div class="card-header d-flex justify-content-between">
                        <div class="lead">
                            <img width="40px" height="40px" class="rounded-circle mr-2" src="{{ Gravatar::src($discussion->getBestReply->owner->email) }}">
                            {{ $discussion->getBestReply->owner->name }}
                        </div>
                        <strong>Best Reply</strong>
                    </div>
                    <div class="card-body py-1">
                        {!! $discussion->getBestReply->reply !!}
                    </div>
                </div>
            @endif
        </div>
    </div>

    @foreach($discussion->replies()->paginate(2) as $reply)
    <div class="card border-primary mb-1">
        <div class="d-flex justify-content-between card-header py-1">
            <div>
                <img height="40px" weight="40px" class="rounded-circle rounded-sm" src="{{ Gravatar::src($reply->owner->email) }}">
                <span class="ml-2">{{ $reply->owner->name }}</span>
            </div>
            <div>
                @auth()
                    @if(auth()->user()->id === $discussion->user_id)
                        <form action="{{ route('best-reply', ['discussion' => $discussion->slug, 'reply' => $reply->id ]) }}" method="POST">
                            @csrf
                            <button type="submit" class="btn btn-primary btn-sm mt-1">mark as best reply</button>
                        </form>
                    @endif
                @endauth

            </div>
        </div>
            <div class="card-body py-1">
                {!! $reply->reply !!}
            </div>
    </div>
    @endforeach
    {{ $discussion->replies()->paginate(2)->links() }}

    <div class="card border-dark">
        <div class="card-header">
            Add a reply
        </div>
        <div class="card-body">
            @auth()
                <form action="{{ route('replies.store', $discussion->slug ) }}" method="POST">
                    @csrf
                    <input id="reply" type="hidden" name="reply">
                    <trix-editor input="reply"></trix-editor>
                    <button class="btn btn-success btn-sm mt-2">Add Reply</button>
                </form>
            @else
                <a href="{{ route('login') }}" class="btn btn-info text-white">Sign in to add a reply</a>
            @endauth
        </div>
    </div>
@endsection
@section('css')
    <link rel="stylesheet" href="{{ asset('css/trix.css') }}">
@endsection

@section('script')
    <script src="{{ asset('js/trix.js') }}"></script>
@endsection